[build]
  publish = "."
  command = "echo 'Static Site - No Build Needed'"

[[headers]]
  for = "/IMG/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/asset/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
