tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary": "#ffb4a8",
              "on-surface-variant": "#e8bcb5",
              "tertiary-fixed": "#e4e2e1",
              "surface-tint": "#ffb4a8",
              "error": "#ffb4ab",
              "on-primary-fixed": "#410000",
              "on-tertiary-container": "#ebe9e9",
              "on-background": "#e2e2e2",
              "outline": "#af8781",
              "surface-container-low": "#1a1c1c",
              "on-secondary": "#313030",
              "surface-dim": "#121414",
              "surface-container-highest": "#333535",
              "outline-variant": "#5e3f3a",
              "on-error": "#690005",
              "inverse-primary": "#c00000",
              "background": "#121414",
              "surface-container-high": "#282a2b",
              "secondary-fixed": "#e5e2e1",
              "on-primary-fixed-variant": "#930000",
              "on-surface": "#e2e2e2",
              "inverse-on-surface": "#2f3131",
              "tertiary": "#c8c6c6",
              "on-primary-container": "#ffe4e0",
              "tertiary-container": "#696969",
              "on-tertiary-fixed-variant": "#474747",
              "on-secondary-container": "#bab8b7",
              "on-secondary-fixed": "#1c1b1b",
              "surface-container": "#1e2020",
              "inverse-surface": "#e2e2e2",
              "on-primary": "#690000",
              "surface-variant": "#333535",
              "secondary-fixed-dim": "#c9c6c5",
              "on-error-container": "#ffdad6",
              "surface": "#121414",
              "secondary-container": "#4a4949",
              "primary-fixed-dim": "#ffb4a8",
              "primary-fixed": "#ffdad4",
              "primary-container": "#d50000",
              "on-tertiary": "#303030",
              "on-secondary-fixed-variant": "#474646",
              "tertiary-fixed-dim": "#c8c6c6",
              "surface-bright": "#37393a",
              "on-tertiary-fixed": "#1b1c1c",
              "error-container": "#93000a",
              "surface-container-lowest": "#0c0f0f",
              "secondary": "#c9c6c5"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "stack-xs": "8px",
              "stack-lg": "48px",
              "gutter": "24px",
              "stack-md": "24px",
              "margin": "48px",
              "container-max": "1440px",
              "unit": "4px"
      },
      "fontFamily": {
              "headline-md": ["Space Grotesk"],
              "headline-lg": ["Space Grotesk"],
              "label-caps": ["Space Grotesk"],
              "display-lg": ["Space Grotesk"],
              "body-lg": ["Inter"],
              "technical-data": ["Space Grotesk"],
              "body-md": ["Inter"],
              "display-md": ["Space Grotesk"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
              "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "0", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "technical-data": ["14px", {"lineHeight": "1", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display-md": ["48px", {"lineHeight": "1.1", "letterSpacing": "0", "fontWeight": "700"}]
      }
    },
  },
};
